# Sets up a separate DEV Supabase project: schema + migrations, test accounts,
# and old-html-version/env.local.js so localhost points at dev.
#   powershell -ExecutionPolicy Bypass -File dev/setup-dev-db.ps1            # full setup (fresh project)
#   powershell -ExecutionPolicy Bypass -File dev/setup-dev-db.ps1 -UsersOnly # just (re)create accounts
param([switch]$UsersOnly)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent

$envFile = @((Join-Path $root '.env.dev'), (Join-Path $PSScriptRoot '.env.dev')) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $envFile) { throw "Missing .env.dev - copy dev/.env.dev.example to .env.dev and fill it in." }
$cfg = @{}
Get-Content $envFile | Where-Object { $_ -match '^\s*([A-Z_]+)\s*=\s*(.*)$' } | ForEach-Object { $cfg[$Matches[1]] = $Matches[2].Trim() }
foreach ($k in 'DEV_DB_URL', 'DEV_SUPABASE_URL', 'DEV_ANON_KEY', 'DEV_SERVICE_ROLE_KEY', 'DEV_USER_PASSWORD') {
  if (-not $cfg[$k]) { throw "$k is not set in .env.dev" }
}
if ($cfg.DEV_SUPABASE_URL -match 'tdxwsgfjkpurtjmgwabr') { throw 'DEV_SUPABASE_URL is the PRODUCTION project. Refusing.' }

# Order taken from git history (the order the migrations were added).
$migrations = @(
  'supabase_schema', 'wasabi_migration', 'storage_video_uploads', 'seed_videos', 'youtube_cleanup',
  'video_feedback_migration', 'drafts_migration', 'review_notifications_migration',
  'more_changes_migration', 'phone_number_migration', 'joe_recordings_migration',
  'recordings_thumbnail_migration', 'notifications_type_constraint_fix', 'push_subscriptions_migration',
  'video_feedback_comments_migration', 'joe_recordings_delete_policy', 'workflow_folders_migration',
  'scripts_migration', 'scripts_assignments_migration'
)

if (-not $UsersOnly) {
  $files = @($migrations | ForEach-Object { Join-Path $root "database/$_.sql" }) + (Join-Path $PSScriptRoot 'dev_extras.sql')
  foreach ($f in $files) {
    Write-Host "-> $(Split-Path $f -Leaf)"
    & psql $cfg.DEV_DB_URL -v ON_ERROR_STOP=1 -q -X -f $f
    if ($LASTEXITCODE -ne 0) { throw "psql failed on $f" }
  }
}

# Test accounts. Roles follow workflow_folders_migration.sql:
#   reviewer = admin + is_reviewer, editor/manager = admin, writers/editors/staff = worker
$users = @(
  @{ email = 'joe@lmp.test';      name = 'Joe (Client)';           role = 'admin';  reviewer = $true  },
  @{ email = 'reviewer@lmp.test'; name = 'Video Reviewer';         role = 'admin';  reviewer = $true  },
  @{ email = 'ravi@lmp.test';     name = 'Ravi (Manager/Editor)';  role = 'admin';  reviewer = $false },
  @{ email = 'writer@lmp.test';   name = 'Script Writer';          role = 'worker'; reviewer = $false },
  @{ email = 'editor@lmp.test';   name = 'Video Editor';           role = 'worker'; reviewer = $false },
  @{ email = 'staff@lmp.test';    name = 'Client Staff';           role = 'worker'; reviewer = $false }
)
$headers = @{ apikey = $cfg.DEV_SERVICE_ROLE_KEY; Authorization = "Bearer $($cfg.DEV_SERVICE_ROLE_KEY)" }
foreach ($u in $users) {
  $body = @{ email = $u.email; password = $cfg.DEV_USER_PASSWORD; email_confirm = $true; user_metadata = @{ full_name = $u.name } } | ConvertTo-Json
  try {
    Invoke-RestMethod -Method Post -Uri "$($cfg.DEV_SUPABASE_URL)/auth/v1/admin/users" -Headers $headers -ContentType 'application/json' -Body $body | Out-Null
    Write-Host "created $($u.email)"
  } catch {
    if ("$_" -match 'already|registered|exists') { Write-Host "exists  $($u.email)" } else { throw }
  }
  $sql = "update public.profiles p set role='$($u.role)', is_reviewer=$($u.reviewer.ToString().ToLower()), full_name='$($u.name)' from auth.users a where a.id=p.id and a.email='$($u.email)';"
  & psql $cfg.DEV_DB_URL -v ON_ERROR_STOP=1 -q -X -c $sql | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "profile update failed for $($u.email)" }
}

$js = "// Generated by dev/setup-dev-db.ps1 - gitignored. Delete to use production.`nwindow.LMP_ENV = { SUPABASE_URL: '$($cfg.DEV_SUPABASE_URL)', SUPABASE_ANON_KEY: '$($cfg.DEV_ANON_KEY)' };`n"
Set-Content -Path (Join-Path $root 'old-html-version/env.local.js') -Value $js -Encoding utf8
Write-Host "`nDone. Wrote old-html-version/env.local.js. Log in at http://localhost:8081 with any @lmp.test account."
